name: Draft release

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Zip dist folder
        run: zip -r dist.zip dist
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build.zip
          asset_name: orgnote-cli-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/octet-stream
